### ISSUE TITLE
NullPointerException rendering TinkersConstruct armour

### ISSUE THREAD

**Issue by AtomicBlom** [bspkrs/bspkrsCore#19]
Not too sure where to post this to so I'll cross post.

Issue: The following error gets repeated every frame rendered on the title screen when a certain entity is selected. (I'm not sure which one, it didn't render at all)

https://gist.github.com/AtomicBlom/f5aaa8e466cc709cb934

Full startup log including the first two exceptions are available here: https://gist.github.com/AtomicBlom/b65974bf22ad849bc302

**Comment by bspkrs** [comment]
Unfortunately there isn't anything simple that I can do to fix this... I already have a try/catch block around the render code in my ticker. FML is catching the exception before it gets to my block, so my code to disable the main menu rendering on exceptions isn't executed.
