### ISSUE TITLE
Extra Configuration for Simple Main Menu Feature

### ISSUE THREAD

**Issue by T145** [bspkrs/bspkrsCore#20]
Could you add an option for each component of the main menu feature? E.g.
```
# Enables player rendering in the main menu [default: true]
showMainMenuPlayer=true
# The player's model position on the screen (will always be the opposite of the mob if enabled) [default: right]
mainMenuPlayerPosition=right

# Enables mob rendering in the main menu [default: true]
showMainMenuMob=true
# The mob's model position on the screen (will always be the opposite of player mob if enabled) [default: left]
mainMenuPlayerPosition=left
```

Sometime it can render mobs from some mods awkwardly, like Mystcraft's books for example, and it would be nice to just have the player if someone doesn't prefer to see the glitchy mob models.

(Would be nice to have this in a 1.7.10 release too)

**Comment by bspkrs** [comment]
No, sorry. I have hated this code ever since I added it, and it will be gone in 1.8 anyway.
